import * as ort from 'onnxruntime-web';
import ortWasmModuleUrl from 'onnxruntime-web/ort-wasm-simd-threaded.mjs?url';
import ortWasmBinaryUrl from 'onnxruntime-web/ort-wasm-simd-threaded.wasm?url';
import { YUNET_MODEL_URL } from '../../camera-ai.config';
import { classifyFaceCount, type CameraFaceDetectionResult, type CameraFaceDetector } from './camera-face-detector';

type Detection = { x: number; y: number; width: number; height: number; score: number };
const INPUT_SIZE = 640;
// Port of OpenCV FaceDetectorYN: BGR uint8 blob, score .5, NMS .3, strides 8/16/32.
export class YuNetFaceDetector implements CameraFaceDetector {
  readonly id = 'yunet'; readonly displayName = 'YuNet'; executionProvider = 'WASM'; private session: ort.InferenceSession | null = null; private canvas: HTMLCanvasElement | null = null;
  async load(): Promise<void> { ort.env.wasm.wasmPaths = { mjs: ortWasmModuleUrl, wasm: ortWasmBinaryUrl }; ort.env.wasm.numThreads = 1; ort.env.wasm.proxy = false; try { this.session = await ort.InferenceSession.create(YUNET_MODEL_URL, { executionProviders: ['webgpu', 'wasm'] }); this.executionProvider = 'WebGPU'; } catch { this.session = await ort.InferenceSession.create(YUNET_MODEL_URL, { executionProviders: ['wasm'] }); } }
  async detect(source: CanvasImageSource, _timestampMs: number): Promise<CameraFaceDetectionResult> { if (!this.session) throw new Error('YuNet has not loaded.'); const start = performance.now(); const { tensor, width, height } = this.toTensor(source); const output = await this.session.run({ [this.session.inputNames[0]]: tensor }); const faceCount = this.nms(this.decode(output, width, height)).length; return { faceCount, predictedClass: classifyFaceCount(faceCount), inferenceMs: performance.now() - start }; }
  dispose(): void { this.session?.release(); this.session = null; this.canvas = null; }
  private toTensor(source: CanvasImageSource) { const canvas = this.canvas ??= document.createElement('canvas'); canvas.width = INPUT_SIZE; canvas.height = INPUT_SIZE; const context = canvas.getContext('2d', { willReadFrequently: true }); if (!context) throw new Error('Unable to create image canvas.');
    // This exact YuNet export has a fixed 640x640 ONNX input. OpenCV's
    // FaceDetectorYN performs this input adaptation internally.
    context.drawImage(source, 0, 0, INPUT_SIZE, INPUT_SIZE); const pixels = context.getImageData(0, 0, INPUT_SIZE, INPUT_SIZE).data; const input = new Float32Array(INPUT_SIZE * INPUT_SIZE * 3); for (let i = 0, p = 0; p < pixels.length; p += 4, i += 1) { input[i] = pixels[p + 2]; input[INPUT_SIZE * INPUT_SIZE + i] = pixels[p + 1]; input[2 * INPUT_SIZE * INPUT_SIZE + i] = pixels[p]; } return { tensor: new ort.Tensor('float32', input, [1, 3, INPUT_SIZE, INPUT_SIZE]), width: INPUT_SIZE, height: INPUT_SIZE }; }
  private decode(outputs: Record<string, ort.Tensor>, width: number, height: number): Detection[] { const byName = (part: string, stride: number) => { const name = this.session!.outputNames.find((value) => value.toLowerCase().includes(part) && value.includes(`_${stride}`)); if (!name) throw new Error(`YuNet output ${part}_${stride} is unavailable.`); return outputs[name].data as Float32Array; }; const faces: Detection[] = []; for (const stride of [8, 16, 32]) { const cls = byName('cls', stride), obj = byName('obj', stride), bbox = byName('bbox', stride), rows = Math.floor(height / stride), cols = Math.floor(width / stride); for (let i = 0; i < cls.length; i += 1) { const score = Math.sqrt(cls[i] * obj[i]); if (score < .5) continue; const x = (i % cols + .5) * stride, y = (Math.floor(i / cols) + .5) * stride, b = i * 4; const w = Math.exp(bbox[b + 2]) * stride, h = Math.exp(bbox[b + 3]) * stride; faces.push({ x: x + bbox[b] * stride - w / 2, y: y + bbox[b + 1] * stride - h / 2, width: w, height: h, score }); } } return faces; }
  private nms(faces: Detection[]): Detection[] { const pending = [...faces].sort((a,b) => b.score-a.score), kept: Detection[] = []; while (pending.length) { const first = pending.shift()!; kept.push(first); for (let i=pending.length-1;i>=0;i-=1) { const other=pending[i], iw=Math.max(0,Math.min(first.x+first.width,other.x+other.width)-Math.max(first.x,other.x)), ih=Math.max(0,Math.min(first.y+first.height,other.y+other.height)-Math.max(first.y,other.y)), unionArea=first.width*first.height+other.width*other.height-iw*ih; if (unionArea && iw*ih/unionArea>.3) pending.splice(i,1); } } return kept; }
}
