import { useEffect, useRef, useState } from "react";
import { PROCTORING_MODELS } from "../config/proctoring-models";
import { PROCTORING_POLICY_VERSION, VISION_POLICY } from "../config/proctoring-policy";
import { proctoringDebugMetricsEnabled, recordProctoringMetric } from "../utils/proctoring-debug-metrics";
import { assessProctoringCapability } from "../utils/proctoring-capability";

type AudioEvent = "AUDIO_ACTIVITY_DETECTED" | "SPEECH_ACTIVITY_DETECTED" | "AUDIO_SIGNAL_DEGRADED";
type State = { active: boolean; startedAt: number | null; recoveredAt: number | null; cooldownUntil: number };
const state = (): State => ({ active: false, startedAt: null, recoveredAt: null, cooldownUntil: 0 });
const median = (values: number[]) => { const sorted = [...values].sort((a, b) => a - b); return sorted[Math.floor(sorted.length / 2)] ?? 0; };
const append = (left: Float32Array, right: Float32Array, limit: number) => { const combined = new Float32Array(left.length + right.length); combined.set(left); combined.set(right, left.length); return combined.slice(Math.max(0, combined.length - limit)); };

export function useAudioProctoring({ active, stream, audioContext, healthy, restartToken = 0, onDetection }: { active: boolean; stream?: MediaStream; audioContext?: AudioContext; healthy: boolean; restartToken?: number; onDetection: (event: AudioEvent, details: string, metadata: Record<string, string | number>) => void }) {
  const [status, setStatus] = useState<"idle" | "calibrating" | "monitoring" | "unavailable">("idle"); const [error, setError] = useState<string | null>(null);
  const states = useRef<Record<AudioEvent, State>>({ AUDIO_ACTIVITY_DETECTED: state(), SPEECH_ACTIVITY_DETECTED: state(), AUDIO_SIGNAL_DEGRADED: state() });
  const workerRef = useRef<Worker | null>(null); const workerReady = useRef(false); const classifierInFlight = useRef(false); const classifierSequence = useRef(0); const latestSequence = useRef(0);
  const baseline = useRef<number | null>(null); const calibration = useRef<number[]>([]); const pcm = useRef(new Float32Array()); const modelPcm = useRef(new Float32Array()); const modelSinceRequest = useRef(0); const analysisSince = useRef(0); const nearZeroStarted = useRef<number | null>(null); const speech = useRef<{ history: Array<{ time: number; confidence: number }>; startedAt: number | null }>({ history: [], startedAt: null });

  useEffect(() => {
    if (!active || !stream || !audioContext || !healthy) return; if (audioContext.state !== "running") { setError("The audio context is not running. Re-enter the exam from the security check."); setStatus("unavailable"); return; }
    baseline.current = null; calibration.current = []; pcm.current = new Float32Array(); modelPcm.current = new Float32Array(); modelSinceRequest.current = 0; analysisSince.current = 0; speech.current = { history: [], startedAt: null }; workerReady.current = false; classifierInFlight.current = false; states.current = { AUDIO_ACTIVITY_DETECTED: state(), SPEECH_ACTIVITY_DETECTED: state(), AUDIO_SIGNAL_DEGRADED: state() }; setError(null); setStatus("calibrating");
    const capability = assessProctoringCapability(stream, audioContext);
    recordProctoringMetric("capability", "audio", { hardwareConcurrency: capability.hardwareConcurrency ?? 0, audioWorkletSupported: capability.audioWorkletSupported, profile: capability.profile });
    const worker = new Worker(new URL("../workers/audio-proctor.worker.ts", import.meta.url), { type: "module" }); workerRef.current = worker; worker.postMessage({ type: "initialize", debug: proctoringDebugMetricsEnabled });
    worker.onmessage = ({ data }) => { if (data.type === "metric") { recordProctoringMetric(data.detector, data.metric, data.values); return; } if (data.type === "ready") { workerReady.current = true; return; } if (data.type === "error") { const message = typeof data.message === "string" ? data.message : "Speech classifier unavailable."; if (import.meta.env.DEV) console.error("[proctoring:audio]", message); setError(message); setStatus("unavailable"); return; } if (data.type === "result") { classifierInFlight.current = false; if (data.sequence !== latestSequence.current) { recordProctoringMetric("audio", "classifier_stale", { sequence: data.sequence }); return; } evaluateSpeech(data.speechConfidence, Date.now()); } };
    const source = audioContext.createMediaStreamSource(stream); let capture: AudioWorkletNode | ScriptProcessorNode | null = null; let silent: GainNode | null = null; let cancelled = false;
    const receive = (samples: Float32Array) => { if (cancelled || document.hidden || !healthy) return; processPcm(samples); };
    const setup = async () => { try { if (!audioContext.audioWorklet) throw new Error("AudioWorklet unsupported"); await audioContext.audioWorklet.addModule(new URL("../workers/audio-capture.worklet.ts", import.meta.url)); if (cancelled) return; const node = new AudioWorkletNode(audioContext, "proctoring-audio-capture", { numberOfOutputs: 0 }); node.port.onmessage = ({ data }) => { if (data.type === "pcm") { receive(data.samples); node.port.postMessage({ type: "ack" }); } else if (data.type === "dropped") recordProctoringMetric("audio", "capture_dropped", { reason: "worklet_backpressure" }); }; source.connect(node); capture = node; recordProctoringMetric("audio", "capture_mode", { mode: "audio_worklet" }); } catch { if (cancelled) return; const node = audioContext.createScriptProcessor(2048, 1, 1); silent = audioContext.createGain(); silent.gain.value = 0; node.onaudioprocess = (event) => receive(new Float32Array(event.inputBuffer.getChannelData(0))); source.connect(node); node.connect(silent); silent.connect(audioContext.destination); capture = node; recordProctoringMetric("audio", "capture_mode", { mode: "script_processor_fallback" }); } };
    const started = Date.now();
    const processPcm = (samples: Float32Array) => {
      pcm.current = append(pcm.current, samples, Math.ceil(audioContext.sampleRate * 6)); analysisSince.current += samples.length; modelPcm.current = append(modelPcm.current, downsample(samples, audioContext.sampleRate, VISION_POLICY.audio.modelSampleRate), VISION_POLICY.audio.modelSampleRate * 2); modelSinceRequest.current += Math.round(samples.length * VISION_POLICY.audio.modelSampleRate / audioContext.sampleRate);
      if (analysisSince.current >= Math.round(audioContext.sampleRate * VISION_POLICY.audio.analysisHopMs / 1_000)) { analysisSince.current = 0; analyse(Date.now(), started); }
      const modelWindow = VISION_POLICY.audio.modelSampleRate * VISION_POLICY.audio.classifierSampleMs / 1_000; const hop = VISION_POLICY.audio.modelSampleRate * VISION_POLICY.audio.classifierHopMs / 1_000;
      if (workerReady.current && !classifierInFlight.current && modelPcm.current.length >= modelWindow && modelSinceRequest.current >= hop) { const sequence = classifierSequence.current + 1; classifierSequence.current = sequence; latestSequence.current = sequence; classifierInFlight.current = true; modelSinceRequest.current = 0; const window = modelPcm.current.slice(-modelWindow); workerRef.current?.postMessage({ type: "classify", sequence, samples: window, sampleRate: VISION_POLICY.audio.modelSampleRate }, [window.buffer]); recordProctoringMetric("audio", "classifier_request", { sequence, pendingRequests: 1, overlapPercent: 50 }); }
    };
    const analyse = (now: number, startedAt: number) => { const samples = pcm.current; if (!samples.length) return; const rms = Math.sqrt(samples.reduce((sum, value) => sum + value * value, 0) / samples.length); const clipping = samples.filter((value) => Math.abs(value) > 0.98).length / samples.length; const dc = Math.abs(samples.reduce((sum, value) => sum + value, 0) / samples.length); if (now - startedAt < VISION_POLICY.audio.calibrationMs) { if (rms >= VISION_POLICY.audio.baselineMin && rms <= VISION_POLICY.audio.baselineMax) calibration.current.push(rms); return; } if (baseline.current === null) { baseline.current = Math.min(VISION_POLICY.audio.baselineMax, Math.max(VISION_POLICY.audio.baselineMin, median(calibration.current))); setStatus("monitoring"); } const base = baseline.current; const threshold = Math.max(base * 3, base + VISION_POLICY.audio.activityFloor); if (rms < threshold * 0.8) baseline.current = Math.min(VISION_POLICY.audio.baselineMax, Math.max(VISION_POLICY.audio.baselineMin, base * 0.995 + rms * 0.005)); const nearZero = rms < VISION_POLICY.audio.nearZeroLevel; nearZeroStarted.current = nearZero ? (nearZeroStarted.current ?? now) : null; evaluate("AUDIO_ACTIVITY_DETECTED", rms > threshold, VISION_POLICY.audio.activityDurationMs, now, rms, base, threshold, 0); evaluate("AUDIO_SIGNAL_DEGRADED", clipping >= VISION_POLICY.audio.clippingRatio || dc >= VISION_POLICY.audio.dcOffset || Boolean(nearZeroStarted.current && now - nearZeroStarted.current >= VISION_POLICY.audio.nearZeroDurationMs), VISION_POLICY.audio.activityDurationMs, now, rms, base, VISION_POLICY.audio.clippingRatio, 0); recordProctoringMetric("audio", "continuous_analysis", { rms, clippingRatio: clipping, dcOffset: dc, baseline: base }); };
    const evaluateSpeech = (confidence: number, now: number) => { const value = speech.current; value.history = [...value.history, { time: now, confidence }].filter((entry) => now - entry.time <= VISION_POLICY.audio.speechWindowSize * VISION_POLICY.audio.classifierHopMs); const qualified = value.history.filter((entry) => entry.confidence >= VISION_POLICY.audio.speechConfidence).length >= VISION_POLICY.audio.speechWindows; if (qualified) value.startedAt ??= value.history[0]?.time ?? now; else value.startedAt = null; const duration = value.startedAt ? now - value.startedAt : 0; evaluate("SPEECH_ACTIVITY_DETECTED", qualified && duration >= VISION_POLICY.audio.speechSustainedMs, 0, now, 0, baseline.current ?? 0, VISION_POLICY.audio.speechConfidence, confidence); };
    const evaluate = (event: AudioEvent, bad: boolean, triggerMs: number, now: number, observed: number, base: number, threshold: number, confidence: number) => { const current = states.current[event]; if (bad) { current.recoveredAt = null; if (!current.active && now >= current.cooldownUntil) { current.startedAt ??= now; if (now - current.startedAt >= triggerMs) { const durationMs = now - current.startedAt; current.active = true; current.startedAt = null; onDetection(event, "An audio monitoring signal was observed.", { detectorName: event === "SPEECH_ACTIVITY_DETECTED" ? "audio_classifier" : "web_audio_continuous", detectorVersion: "1.0.1", modelVersion: PROCTORING_MODELS.speech.version, policyVersion: PROCTORING_POLICY_VERSION, incidentId: window.crypto.randomUUID(), confidence, durationMs, baselineLevel: base, observedLevel: observed, threshold, cooldownMs: VISION_POLICY.audio.cooldownMs, sampleTimestamp: new Date().toISOString() }); } } return; } current.startedAt = null; if (current.active) { current.recoveredAt ??= now; if (now - current.recoveredAt >= VISION_POLICY.audio.recoveryMs) { current.active = false; current.recoveredAt = null; current.cooldownUntil = now + VISION_POLICY.audio.cooldownMs; } } };
    void setup(); return () => { cancelled = true; worker.postMessage({ type: "dispose" }); window.setTimeout(() => worker.terminate(), 100); workerRef.current = null; source.disconnect(); capture?.disconnect(); silent?.disconnect(); };
  // AudioContext originates from preflight and is reused for the active attempt.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [active, stream, audioContext, healthy, restartToken]);
  return { status, error };
}

function downsample(samples: Float32Array, sourceRate: number, targetRate: number) { if (sourceRate === targetRate) return samples.slice(); const ratio = sourceRate / targetRate; const length = Math.floor(samples.length / ratio); const output = new Float32Array(length); for (let index = 0; index < length; index += 1) output[index] = samples[Math.min(samples.length - 1, Math.floor(index * ratio))]; return output; }
