import { useRef, useState } from 'react';
import { CAMERA_AI_CONFIG } from '../../anti-cheat/camera-ai.config';
import { BlazeFaceShortDetector } from '../../anti-cheat/camera/detectors/blazeface-short-detector';
import { MediaPipeFaceLandmarkerDetector } from '../../anti-cheat/camera/detectors/mediapipe-face-landmarker-detector';
import { Scrfd10GfDetector } from '../../anti-cheat/camera/detectors/scrfd-10gf-detector';
import { YuNetFaceDetector } from '../../anti-cheat/camera/detectors/yunet-face-detector';
import type { CameraFaceDetector, FaceCountClass } from '../../anti-cheat/camera/detectors/camera-face-detector';
import { ShadowIncidentFilter, download, summarize, toCsv, type CameraScenario, type EvaluationMode, type EvaluationRow } from '../../anti-cheat/camera/model-evaluation';

const scenarios: CameraScenario[] = ['one_face_normal', 'one_face_glasses', 'one_face_head_movement', 'one_face_far', 'one_face_partial_occlusion', 'one_face_low_light', 'no_face', 'multiple_faces_side', 'multiple_faces_background', 'multiple_faces_enter_leave'];
const models = [{ id: 'face_landmarker', label: 'Face Landmarker', create: () => new MediaPipeFaceLandmarkerDetector() }, { id: 'blazeface_short', label: 'BlazeFace Short', create: () => new BlazeFaceShortDetector() }, { id: 'yunet', label: 'YuNet', create: () => new YuNetFaceDetector() }, { id: 'scrfd_10gf', label: 'SCRFD-10GF', create: () => new Scrfd10GfDetector() }] as const;

export function CameraModelComparison() {
  const video = useRef<HTMLVideoElement>(null); const rows = useRef<EvaluationRow[]>([]); const stop = useRef<(() => void) | null>(null);
  const [groundTruth, setGroundTruth] = useState<FaceCountClass | ''>(''); const [scenario, setScenario] = useState<CameraScenario>('one_face_normal'); const [duration, setDuration] = useState(30); const [status, setStatus] = useState('Idle'); const [summary, setSummary] = useState<ReturnType<typeof summarize>>([]); const [selected, setSelected] = useState<string[]>(models.map((model) => model.id));
  const begin = async (mode: EvaluationMode) => {
    if (!groundTruth) { setStatus('Select ground truth first.'); return; }
    const chosen = mode === 'same_frame' ? models.filter((model) => selected.includes(model.id)) : models.filter((model) => `${model.id}_performance` === mode);
    if (!chosen.length) { setStatus('Select at least one model.'); return; }
    let stream: MediaStream | null = null; const detectors: CameraFaceDetector[] = chosen.map((model) => model.create());
    try { stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: false }); if (!video.current) throw new Error('Camera preview is unavailable.'); video.current.srcObject = stream; await video.current.play(); if (!video.current.videoWidth || !video.current.videoHeight) await new Promise<void>((resolve) => video.current!.addEventListener('loadeddata', () => resolve(), { once: true })); if (!video.current.videoWidth || !video.current.videoHeight) throw new Error('Camera frame has no dimensions.'); setStatus('Loading models...'); await Promise.all(detectors.map((detector) => detector.load())); }
    catch (error) { detectors.forEach((detector) => detector.dispose()); stream?.getTracks().forEach((track) => track.stop()); setStatus(error instanceof Error ? `Model load failed: ${error.message}` : 'Model load failed.'); return; }
    const sessionId = crypto.randomUUID(), filters = new Map(detectors.map((detector) => [detector.id, new ShadowIncidentFilter()])); let busy = false, timer: number | null = null, ended = false;
    const finish = () => { if (ended) return; ended = true; if (timer) window.clearInterval(timer); detectors.forEach((detector) => detector.dispose()); stream!.getTracks().forEach((track) => track.stop()); setSummary(summarize(rows.current)); setStatus('Complete. Export data or run another condition.'); };
    const sample = async () => { if (busy || !video.current) return; busy = true; const timestamp = performance.now(); try { const snapshot = document.createElement('canvas'); snapshot.width = video.current.videoWidth; snapshot.height = video.current.videoHeight; snapshot.getContext('2d')?.drawImage(video.current, 0, 0); for (const detector of detectors) { const result = await detector.detect(snapshot, timestamp); rows.current.push({ session_id: sessionId, scenario, ground_truth_class: groundTruth, timestamp_ms: timestamp, model_id: detector.id, predicted_face_count: result.faceCount, predicted_class: result.predictedClass, correct: result.predictedClass === groundTruth, inference_ms: result.inferenceMs, execution_provider: detector.executionProvider, incident: filters.get(detector.id)!.observe(result, timestamp) }); } setSummary(summarize(rows.current)); } catch (error) { setStatus(error instanceof Error ? error.message : 'Inference failed.'); } finally { busy = false; } };
    setStatus(`${mode}: running at ${CAMERA_AI_CONFIG.mainThreadMaxFps} FPS.`); await sample(); timer = window.setInterval(() => void sample(), 1000 / CAMERA_AI_CONFIG.mainThreadMaxFps); window.setTimeout(finish, duration * 1000); stop.current = finish;
  };
  return <main className="min-h-screen bg-slate-950 p-6 text-slate-100"><h1 className="text-2xl font-bold">Camera 4-Model Evaluation</h1><p className="mt-2 text-slate-300">Development-only. Each selected detector receives the same canvas snapshot; no frames leave this browser.</p><div className="mt-5 grid gap-3 md:grid-cols-3"><label>Ground truth <select value={groundTruth} onChange={(e) => setGroundTruth(e.target.value as FaceCountClass)}><option value="">Required</option>{['NO_FACE','ONE_FACE','MULTIPLE_FACES'].map((value) => <option key={value}>{value}</option>)}</select></label><label>Scenario <select value={scenario} onChange={(e) => setScenario(e.target.value as CameraScenario)}>{scenarios.map((value) => <option key={value}>{value}</option>)}</select></label><label>Duration seconds <input type="number" min="1" value={duration} onChange={(e) => setDuration(Number(e.target.value))} /></label></div><fieldset className="mt-4"><legend>Accuracy models</legend>{models.map((model) => <label className="mr-4" key={model.id}><input type="checkbox" checked={selected.includes(model.id)} onChange={() => setSelected((current) => current.includes(model.id) ? current.filter((id) => id !== model.id) : [...current, model.id])} /> {model.label}</label>)}</fieldset><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => void begin('same_frame')}>Run selected same-frame accuracy</button>{models.map((model) => <button key={model.id} onClick={() => void begin(`${model.id}_performance` as EvaluationMode)}>{model.label} performance</button>)}<button onClick={() => stop.current?.()}>Stop</button><button onClick={() => { rows.current = []; setSummary([]); }}>Reset</button><button onClick={() => download('camera_4_model_raw.csv', toCsv(rows.current), 'text/csv')}>Export raw CSV</button><button onClick={() => download('camera_4_model_results.json', JSON.stringify({ rows: rows.current, summary }, null, 2), 'application/json')}>Export JSON</button><button onClick={() => download('camera_4_model_summary.csv', toCsv(summary), 'text/csv')}>Export summary</button></div><p className="mt-3">{status} WebGPU: {navigator.gpu ? 'available' : 'unavailable'}; target: 4 FPS.</p><video ref={video} className="mt-4 max-h-64 rounded" muted playsInline /><table className="mt-5 w-full text-left"><thead><tr><th>Metric</th>{models.map((model) => <th key={model.id}>{model.label}</th>)}</tr></thead><tbody>{['frames','accuracy','macro_f1','avg_inference_ms','p95_inference_ms','effective_fps','false_incidents','missed_incidents'].map((metric) => <tr key={metric}><td>{metric}</td>{models.map((model) => <td key={model.id}>{String(summary.find((item) => item.model_id === model.id)?.[metric as keyof (typeof summary)[number]] ?? '-')}</td>)}</tr>)}</tbody></table></main>;
}
