import { useEffect, useRef, useState } from "react";
import { AlertCircle, CheckCircle, Download, Eye, FileText, LoaderCircle, RefreshCw, Search } from "lucide-react";
import { toast } from "sonner";
import { adminAuditLogService } from "../../services/admin-audit-log.service";
import type { AdminAuditListParams, AdminAuditLog, AdminAuditLogDetail, AdminAuditStats } from "../../types/admin-audit-log";
import { Button } from "../ui/button";
import { Card } from "../ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "../ui/dialog";
import { Input } from "../ui/input";

const initialFilters: AdminAuditListParams = { page: 1, page_size: 25 };
const dateTime = (value: string | null) => value ? new Date(value).toLocaleString() : "-";
const target = (item: AdminAuditLog) => `${item.entity.type.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase())} #${item.entity.id}`;
const metadataLabel = (key: string) => key.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export function AuditLogPage() {
  const [filters, setFilters] = useState<AdminAuditListParams>(initialFilters);
  const [items, setItems] = useState<AdminAuditLog[]>([]);
  const [total, setTotal] = useState(0);
  const [stats, setStats] = useState<AdminAuditStats | null>(null);
  const [actions, setActions] = useState<{ code: string; label: string; category: string }[]>([]);
  const [categories, setCategories] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [selected, setSelected] = useState<AdminAuditLogDetail | null>(null);
  const requestVersion = useRef(0);

  const load = async () => {
    const version = ++requestVersion.current; setLoading(true); setError(false);
    try { const result = await adminAuditLogService.list(filters); if (version === requestVersion.current) { setItems(result.items); setTotal(result.total); } }
    catch { if (version === requestVersion.current) setError(true); }
    finally { if (version === requestVersion.current) setLoading(false); }
  };
  useEffect(() => { void load(); }, [filters]);
  useEffect(() => { void Promise.all([adminAuditLogService.getStats(), adminAuditLogService.getActions()]).then(([nextStats, catalog]) => { setStats(nextStats); setActions(catalog.actions); setCategories(catalog.categories); }).catch(() => toast.error("Audit log filters could not be loaded.")); }, []);
  const setFilter = (key: keyof AdminAuditListParams, value: string) => setFilters((current) => ({ ...current, [key]: value || undefined, page: 1 }));
  const showDetail = async (id: number) => { try { setSelected(await adminAuditLogService.get(id)); } catch { toast.error("Audit event details could not be loaded."); } };
  const exportCsv = async () => { try { const blob = await adminAuditLogService.exportCsv(filters); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `audit-logs-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); } catch { toast.error("Audit log export could not be completed."); } };
  const start = total ? (Number(filters.page) - 1) * Number(filters.page_size) + 1 : 0;
  const end = Math.min(start + items.length - 1, total);

  return <main className="mx-auto max-w-7xl px-4 py-6 md:px-6"><div className="mb-6 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-semibold text-gray-900">Audit Log</h2><p className="mt-1 text-sm text-gray-500">Review important administrative and system changes across the examination platform.</p></div><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={`size-4 ${loading ? "animate-spin" : ""}`} />Refresh</Button></div>
    <div className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Total Events", stats?.total_events], ["Last 24 Hours", stats?.events_last_24h], ["Admin Actions", stats?.admin_actions], ["Failed Operations", stats?.failed_operations]].map(([label, value]) => <Card key={label as string} className="border-gray-200 p-4"><p className="text-2xl font-semibold text-gray-900">{value ?? "-"}</p><p className="text-sm text-gray-500">{label}</p></Card>)}</div>
    <Card className="mb-5 p-4"><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6"><div className="relative xl:col-span-2"><Search className="absolute left-3 top-2.5 size-4 text-gray-400" /><Input className="pl-9" value={filters.search ?? ""} onChange={(event) => setFilter("search", event.target.value)} placeholder="Search actor, action, target..." /></div><select value={filters.actor_role ?? ""} onChange={(event) => setFilter("actor_role", event.target.value)} className="h-9 rounded-md border border-gray-200 bg-white px-3 text-sm"><option value="">All Roles</option><option value="admin">Admin</option><option value="teacher">Teacher</option><option value="system">System</option></select><select value={filters.category ?? ""} onChange={(event) => setFilter("category", event.target.value)} className="h-9 rounded-md border border-gray-200 bg-white px-3 text-sm"><option value="">All Categories</option>{categories.map((item) => <option key={item} value={item}>{item.replace(/_/g, " ")}</option>)}</select><select value={filters.action ?? ""} onChange={(event) => setFilter("action", event.target.value)} className="h-9 rounded-md border border-gray-200 bg-white px-3 text-sm"><option value="">All Actions</option>{actions.map((item) => <option key={item.code} value={item.code}>{item.label}</option>)}</select><select value={filters.outcome ?? ""} onChange={(event) => setFilter("outcome", event.target.value)} className="h-9 rounded-md border border-gray-200 bg-white px-3 text-sm"><option value="">All Outcomes</option><option value="SUCCESS">Success</option><option value="FAILED">Failed</option></select><Input type="date" value={filters.date_from ?? ""} onChange={(event) => setFilter("date_from", event.target.value)} /><Input type="date" value={filters.date_to ?? ""} onChange={(event) => setFilter("date_to", event.target.value)} /><Button variant="outline" onClick={() => setFilters(initialFilters)}>Reset Filters</Button><Button onClick={() => void exportCsv()}><Download className="size-4" />Export</Button></div></Card>
    <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase tracking-wide text-gray-500"><tr>{["Time", "Actor", "Role", "Action", "Target", "Outcome", "Details"].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={7} className="px-4 py-10 text-center text-gray-500"><LoaderCircle className="mr-2 inline size-4 animate-spin" />Loading audit logs...</td></tr> : error ? <tr><td colSpan={7} className="px-4 py-10 text-center text-gray-500">Audit logs could not be loaded. <Button size="sm" variant="outline" onClick={() => void load()}>Retry</Button></td></tr> : items.length === 0 ? <tr><td colSpan={7} className="px-4 py-10 text-center text-gray-500"><FileText className="mx-auto mb-2 size-7" />No audit events match the current filters.</td></tr> : items.map((item) => <tr key={item.audit_log_id} className="border-t border-gray-100"><td className="px-4 py-3 text-xs text-gray-500">{dateTime(item.created_at)}</td><td className="px-4 py-3"><p className="font-medium">{item.actor.full_name ?? (item.actor.school_id ? item.actor.school_id : "System")}</p>{item.actor.school_id && <p className="text-xs text-gray-500">{item.actor.school_id}</p>}</td><td className="px-4 py-3"><span className="rounded-full bg-gray-100 px-2 py-1 text-xs">{item.actor.role ?? "-"}</span></td><td className="px-4 py-3">{item.action_label}</td><td className="px-4 py-3">{target(item)}</td><td className="px-4 py-3"><span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-xs ${item.outcome === "SUCCESS" ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{item.outcome === "SUCCESS" ? <CheckCircle className="size-3" /> : <AlertCircle className="size-3" />}{item.outcome === "SUCCESS" ? "Success" : "Failed"}</span></td><td className="px-4 py-3"><Button size="sm" variant="outline" onClick={() => void showDetail(item.audit_log_id)}><Eye className="size-4" />View</Button></td></tr>)}</tbody></table></div></Card>
    <div className="mt-4 flex items-center justify-between text-sm text-gray-600"><span>Showing {start}-{end} of {total} events</span><div className="flex items-center gap-2"><select value={String(filters.page_size)} onChange={(event) => setFilters((current) => ({ ...current, page: 1, page_size: Number(event.target.value) }))} className="h-8 rounded border px-2"><option value="25">25</option><option value="50">50</option><option value="100">100</option></select><Button size="sm" variant="outline" disabled={Number(filters.page) <= 1} onClick={() => setFilters((current) => ({ ...current, page: Number(current.page) - 1 }))}>Previous</Button><span>Page {filters.page}</span><Button size="sm" variant="outline" disabled={end >= total} onClick={() => setFilters((current) => ({ ...current, page: Number(current.page) + 1 }))}>Next</Button></div></div>
    <Dialog open={selected !== null} onOpenChange={(open) => { if (!open) setSelected(null); }}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>Audit Event #{selected?.audit_log_id}</DialogTitle><DialogDescription>{selected?.action_label} ({selected?.action})</DialogDescription></DialogHeader>{selected && <div className="grid gap-3 text-sm sm:grid-cols-2"><p><strong>Time:</strong> {dateTime(selected.created_at)}</p><p><strong>Outcome:</strong> {selected.outcome}</p><p><strong>Actor:</strong> {selected.actor.full_name ?? "System"}</p><p><strong>School ID:</strong> {selected.actor.school_id ?? "-"}</p><p><strong>Role:</strong> {selected.actor.role ?? "system"}</p><p><strong>Target:</strong> {selected.entity_type} #{selected.entity_id}</p><p><strong>Request ID:</strong> {selected.request_id ?? "-"}</p><p><strong>Client IP:</strong> {selected.client_ip ?? "-"}</p><p className="sm:col-span-2"><strong>Browser / User Agent:</strong> {selected.user_agent ?? "-"}</p><div className="sm:col-span-2 rounded-lg bg-gray-50 p-3"><strong>Metadata / Changes</strong><dl className="mt-2 grid gap-2 sm:grid-cols-2">{Object.entries(selected.metadata).length ? Object.entries(selected.metadata).map(([key, value]) => <div key={key}><dt className="text-xs text-gray-500">{metadataLabel(key)}</dt><dd>{Array.isArray(value) ? value.join(", ") : String(value ?? "-")}</dd></div>) : <span className="text-gray-500">No additional metadata.</span>}</dl></div></div>}</DialogContent></Dialog>
  </main>;
}
