"""support question revision approval workflow

Revision ID: 0e82dc4b99b6
Revises: b8e31c4d7a92
Create Date: 2026-07-23 16:45:13.317415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0e82dc4b99b6'
down_revision: Union[str, Sequence[str], None] = 'b8e31c4d7a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_revision', sa.Column('version_number', sa.Integer(), nullable=False))
    op.add_column('question_revision', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('question_revision', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('question_revision', sa.Column('rejection_reason', sa.String(length=500), nullable=True))
    op.add_column('question_revision', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('question_revision', 'question_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.create_index('ix_question_revision_pending_lookup', 'question_revision', ['question_id', 'question_status', 'edited_by'], unique=False)
    op.create_unique_constraint('uq_question_revision_question_version', 'question_revision', ['question_id', 'version_number'])
    op.create_foreign_key(None, 'question_revision', 'user', ['approved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_revision', type_='foreignkey')
    op.drop_constraint('uq_question_revision_question_version', 'question_revision', type_='unique')
    op.drop_index('ix_question_revision_pending_lookup', table_name='question_revision')
    op.alter_column('question_revision', 'question_status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_column('question_revision', 'updated_at')
    op.drop_column('question_revision', 'rejection_reason')
    op.drop_column('question_revision', 'approved_at')
    op.drop_column('question_revision', 'approved_by')
    op.drop_column('question_revision', 'version_number')
    # ### end Alembic commands ###
