"""add user account management fields

Revision ID: 14caa6f1995f
Revises: 0e82dc4b99b6
Create Date: 2026-07-24 18:00:04.033886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14caa6f1995f'
down_revision: Union[str, Sequence[str], None] = '0e82dc4b99b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_locked', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('user', sa.Column('locked_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('locked_by', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['locked_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user', 'user', ['deleted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'deleted_by')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'locked_by')
    op.drop_column('user', 'locked_at')
    op.drop_column('user', 'is_locked')
    # ### end Alembic commands ###
