"""add sequential navigation setting

Revision ID: 394eab1e3799
Revises: d5f9b2e3a014
Create Date: 2026-08-04 19:26:55.187206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '394eab1e3799'
down_revision: Union[str, Sequence[str], None] = 'd5f9b2e3a014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_setting', sa.Column('sequential_navigation', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_setting', 'sequential_navigation')
    # ### end Alembic commands ###
