"""support student attempt autosave snapshot terminate

Revision ID: 73a66610d3da
Revises: 6f3a2b9c1d40
Create Date: 2026-07-28 10:57:46.719676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a66610d3da'
down_revision: Union[str, Sequence[str], None] = '6f3a2b9c1d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('status', sa.Enum('in_progress', 'submitted', 'terminated', name='attemptstatus'), server_default=sa.text("'in_progress'"), nullable=False))
    op.add_column('attempt', sa.Column('last_saved_at', sa.DateTime(), nullable=True))
    op.add_column('attempt', sa.Column('termination_reason', sa.String(length=255), nullable=True))
    op.add_column('attempt_question', sa.Column('question_text_snapshot', sa.Text(), nullable=True))
    op.add_column('attempt_question', sa.Column('question_type_snapshot', sa.String(length=30), nullable=True))
    op.add_column('attempt_question', sa.Column('question_point_snapshot', sa.Integer(), nullable=True))
    op.add_column('attempt_question', sa.Column('options_snapshot', sa.JSON(), nullable=True))
    # Backfill dữ liệu attempt cũ
    op.execute(
        """
        UPDATE attempt
        SET status = CASE
            WHEN submitted_at IS NOT NULL THEN 'submitted'
            WHEN end_time IS NOT NULL THEN 'terminated'
            ELSE 'in_progress'
        END
        """
    )

    # Backfill snapshot cho attempt_question cũ
    op.execute(
        """
        UPDATE attempt_question aq
        JOIN question q
            ON q.question_id = aq.question_id
        JOIN attempt a
            ON a.attempt_id = aq.attempt_id
        LEFT JOIN exam_question eq
            ON eq.exam_id = a.exam_id
            AND eq.question_id = aq.question_id
        SET
            aq.question_text_snapshot = q.question_text,
            aq.question_type_snapshot = q.question_type,
            aq.question_point_snapshot = eq.question_point
        WHERE aq.question_text_snapshot IS NULL
        """
    )   
    op.create_unique_constraint('uq_mcq_answers_attempt_question', 'mcq_answers', ['attempt_id', 'question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_mcq_answers_attempt_question', 'mcq_answers', type_='unique')
    op.drop_column('attempt_question', 'options_snapshot')
    op.drop_column('attempt_question', 'question_point_snapshot')
    op.drop_column('attempt_question', 'question_type_snapshot')
    op.drop_column('attempt_question', 'question_text_snapshot')
    op.drop_column('attempt', 'termination_reason')
    op.drop_column('attempt', 'last_saved_at')
    op.drop_column('attempt', 'status')
    # ### end Alembic commands ###
