"""add_totalpoints_passingscore

Revision ID: c520a6e83086
Revises: 0f9d2c7b3a11
Create Date: 2026-07-20 16:49:39.618082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c520a6e83086'
down_revision: Union[str, Sequence[str], None] = '0f9d2c7b3a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('total_points', sa.Integer(), server_default='100', nullable=True))
    op.add_column('exam', sa.Column('passing_score', sa.Integer(), server_default='50', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'passing_score')
    op.drop_column('exam', 'total_points')
    # ### end Alembic commands ###