"""add teacher subject and question revision

Revision ID: db5770a72011
Revises: 9c7d2f1a6b40
Create Date: 2026-07-17 17:22:38.524983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db5770a72011'
down_revision: Union[str, Sequence[str], None] = '9c7d2f1a6b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_subject',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=20), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'subject_id')
    )
    op.create_table('question_revision',
    sa.Column('revision_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=255), nullable=False),
    sa.Column('question_difficulties', sa.String(length=20), nullable=True),
    sa.Column('question_type', sa.String(length=20), nullable=True),
    sa.Column('subject_id', sa.String(length=20), nullable=True),
    sa.Column('question_status', sa.String(length=20), nullable=True),
    sa.Column('options_snapshot', sa.JSON(), nullable=True),
    sa.Column('chapter_ids_snapshot', sa.JSON(), nullable=True),
    sa.Column('lo_ids_snapshot', sa.JSON(), nullable=True),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.alter_column('attempt', 'start_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('attempt', 'end_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('attempt', 'submitted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('exam_event', 'event_timestamp',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('options', 'is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_foreign_key(None, 'options', 'question', ['question_id'], ['question_id'], ondelete='CASCADE')
    op.alter_column('question', 'question_difficulties',
               existing_type=mysql.ENUM('easy', 'medium', 'hard'),
               nullable=True)
    op.alter_column('question', 'subject_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('question', 'subject_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('question', 'question_difficulties',
               existing_type=mysql.ENUM('easy', 'medium', 'hard'),
               nullable=False)
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.alter_column('options', 'is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('exam_event', 'event_timestamp',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('attempt', 'submitted_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('attempt', 'end_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('attempt', 'start_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_table('question_revision')
    op.drop_table('teacher_subject')
    # ### end Alembic commands ###
